fabric_name: CSU

local_users:
  # Define a new user, which is called "ansible"
  - name: admin
    disabled: true

# CloudVision Portal definitions
cvp_instance_ips:
  - apiserver.cv-staging.corp.arista.io
#  - cv-staging.corp.arista.io
terminattr_disable_aaa: true
# DNS Server
name_servers:
  - 8.8.8.8

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Management VRF
custom_structured_configuration_ntp:
  local_interface:
    name: Management0
    vrf: mgmt
  servers:
    - name: 132.163.96.3
      vrf: mgmt

mgmt_interface: Management0
mgmt_interface_vrf: mgmt
mgmt_gateway: 192.168.100.1
mgmt_vrf_routing: yes

snmp_server:
  contact: "noc@colostate.edu"
  hosts:
    - host: "10.100.201.199"
      vrf: mgmt
      version: 2c
      community: "csUn0c"
  communities:
    - name: csUn0c
      access: ro
banners:
  login: |
    ******************************************************************* NOTICE TO USERS *******************************************************************


    This is an official computer system and is the property of Colorado State University. It is for authorized users only. Unauthorized users are prohibited. 
    Users (authorized or unauthorized) have no explicit or implicit expectation of privacy. Any or all uses of this system may be subject to one or more of 
    the following actions- interception, monitoring, recording, auditing, inspection and disclosing to security personnel and law enforcement personnel,
    as well as authorized officials of other agencies, both domestic and foreign. By using this system, the user consents to these actions. Unauthorized 
    or improper use of this system may result in administrative disciplinary action and civil and criminal penalties. 
    By accessing this system you indicate your awareness of and consent to these terms and conditions of use. 
    Discontinue access immediately if you do not agree to the conditions stated in this notice.

    
    ******************************************************************* NOTICE TO USERS *******************************************************************
    EOF

logging:
  vrfs:
    - name: mgmt
      # Source interface name.
      source_interface: Management0
      hosts:
        - name: 129.82.111.172

#### CSU Possible additions        
ip_access_lists:
  - name: mgmt-acl
    # Can't run in vEOS
    # counters_per_entry: true
    entries:
      - sequence: 10
        action: permit
        protocol: ip
        source: 192.168.1.0/24
        destination: any
      - sequence: 20
        action: permit
        protocol: ip
        source: 192.168.3.0/24
        destination: any      
      - sequence: 30
        action: permit
        protocol: ip
        source: 192.168.100.0/24
        destination: any   
management_ssh:
  access_groups:
    - name: mgmt-acl
      vrf: mgmt

aaa_authorization:
  exec:
    default: local

event_handlers:
  - name: renameInterfaces
    actions:
      bash_command: "bash /mnt/flash/renameInterfaces.sh"
    trigger: on-boot 
    delay: 30
# eos_cli: "event-handler renameInterfaces
#    trigger on-boot
#    action bash bash /mnt/flash/renameInterfaces.sh
#    delay 30"
